apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-postgres-auth
  namespace: sonarqube
type: Opaque
stringData:
  postgres-password: "superStrongAdminPass"  
  password: "sonarqubeDBpass123"             
  username: "bn_sonarqube"                   
  database: "bitnami_sonarqube"              
