apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metric-server
  namespace: argocd
  labels:
    type: monitoring
    app: metric-server
spec:
  project: platforms-tools
  sources:
    - repoURL: 'git@gitlab.com:connect2465239/plateng/helm-charts.git'
      targetRevision: develop
      ref: values
    - repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
      chart: metrics-server
      targetRevision: "3.8.2"
      helm:
        releaseName: metric-server
        valueFiles:
          - $values/CHARTS/metric-server/dev-values.yaml
  destination:
    namespace: kube-system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
