apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    type: monitoring
    app: metrics-server
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/la-belle-femme/251017-helm-charts.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://kubernetes-sigs.github.io/metrics-server/'
      chart: metrics-server
      targetRevision: "3.8.2"
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/CHARTS/metrics-server/dev-values.yaml
  destination:
    namespace: kube-system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true