apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platforms-tools
  namespace: argocd
spec:
  description: Platform Tools Applications
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'