apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: s10
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:1.25
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: app-secret
