apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: s10
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 8080 # container port
  type: LoadBalancer
