apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store
  namespace: argocd
  labels:
    type: csi-secrets-store
spec:
  project: plateng
  source:
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: secrets-store-csi-driver
    targetRevision: 1.5.3
    helm:
      parameters:
        - name: syncSecret.enabled
          value: "false"           
        - name: enableSecretRotation
          value: "true"           
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
