apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    namespace: external-secrets
    version: v0.18.2
    valuesInline:
      installCRDs: true
patches:
  - patch: |
      $patch: delete
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: external-secrets
    target:
      kind: ServiceAccount
      name: external-secrets

resources:
  - cluster-secret-store.yaml
  - grafana-secret-controller.yaml
  - splunk-otel-secret-controller.yaml
