apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  labels:
    type: k8s
spec:
  project: plateng
  sources:
    - repoURL: 'https://git.kbr.com/devops/kube-services/kyverno.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://kyverno.github.io/kyverno'
      chart: kyverno
      targetRevision: "3.5.2"
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/overrides/kyverno-lower.yaml
  destination:
    namespace: kyverno
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true