apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    type: k8s
spec:
  project: plateng
  source:
    repoURL: 'https://git.test.com/test.git'
    path: 'base/infrastructure/metrics-server/app'
    targetRevision: HEAD
  destination:
    namespace: kube-system
    name: 'in-cluster'
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true