apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://ec2-3-209-232-107.compute-1.amazonaws.com:8200"   # 👈 VM IP where Vault is running
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:               # simplest for dev/test
          name: vault-token
          key: token
          namespace: external-secrets
